//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TechStokDBEntities : DbContext
    {
        public TechStokDBEntities()
            : base("name=TechStokDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Kategori> tbl_Kategori { get; set; }
        public virtual DbSet<tbl_Kullanicilar> tbl_Kullanicilar { get; set; }
        public virtual DbSet<tbl_Loglar> tbl_Loglar { get; set; }
        public virtual DbSet<tbl_Parca> tbl_Parca { get; set; }
        public virtual DbSet<tbl_Siparis> tbl_Siparis { get; set; }
        public virtual DbSet<tbl_SiparisDetay> tbl_SiparisDetay { get; set; }
        public virtual DbSet<tbl_Yedekleme> tbl_Yedekleme { get; set; }
        public virtual DbSet<tbl_Yetki> tbl_Yetki { get; set; }
        public virtual DbSet<vKullanicilar> vKullanicilars { get; set; }
        public virtual DbSet<vUrunler> vUrunlers { get; set; }
        public virtual DbSet<vSiparis> vSiparis1 { get; set; }
        public virtual DbSet<vw_TopSellingProducts> vw_TopSellingProducts { get; set; }
    }
}
