//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Siparis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Siparis()
        {
            this.tbl_SiparisDetay = new HashSet<tbl_SiparisDetay>();
        }
    
        public int SiparisId { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<System.DateTime> SiparisTarihi { get; set; }
        public Nullable<decimal> ToplamTutar { get; set; }
        public string SiparisDurumu { get; set; }
        public Nullable<System.DateTime> TestimTarihi { get; set; }
    
        public virtual tbl_Kullanicilar tbl_Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SiparisDetay> tbl_SiparisDetay { get; set; }
    }
}
