//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Yedekleme
    {
        public int YedekId { get; set; }
        public Nullable<System.DateTime> YedeklemeTarihi { get; set; }
        public string YedekDosyaYolu { get; set; }
        public Nullable<int> YedekAlanKullaniciID { get; set; }
    
        public virtual tbl_Kullanicilar tbl_Kullanicilar { get; set; }
    }
}
