//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Loglar
    {
        public int LogId { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<System.DateTime> IslemTarihi { get; set; }
        public string Islem { get; set; }
    
        public virtual tbl_Kullanicilar tbl_Kullanicilar { get; set; }
    }
}
