//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SiparisDetay
    {
        public int SiparisDetayId { get; set; }
        public Nullable<int> SiparisID { get; set; }
        public Nullable<int> ParcaID { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<decimal> BirimFiyati { get; set; }
        public Nullable<decimal> AraToplam { get; set; }
    
        public virtual tbl_Parca tbl_Parca { get; set; }
        public virtual tbl_Siparis tbl_Siparis { get; set; }
    }
}
