//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSiparis
    {
        public int SiparisId { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<int> ParcaID { get; set; }
        public string ParcaAdi { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<decimal> AraToplam { get; set; }
        public Nullable<decimal> ToplamTutar { get; set; }
        public Nullable<System.DateTime> SiparisTarihi { get; set; }
        public string SiparisDurumu { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public Nullable<decimal> BirimFiyati { get; set; }
    }
}
